spring.application.name=backend

# ================================
# Database Configuration
# ================================
spring.datasource.url=jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.xyvpenjqbszdhandkvzb
spring.datasource.password=Arpan908790
spring.datasource.driver-class-name=org.postgresql.Driver

# ================================
# JPA/Hibernate Configuration
# ================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=false

# ================================
# Razorpay
# ================================
razorpay.key_id=YOUR_RAZORPAY_KEY
razorpay.key_secret=YOUR_RAZORPAY_SECRET

# ================================
# JWT
# ================================
jwt.secret=mysupersecretkeymysupersecretkey1234567890
jwt.expirationMinutes=60